### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by trymzet** [dyvenia/elt_workshop#1]
# ELT workshops - TODO

## 0. Intro
- [x] #7

## 1. Set up
- [x] #15
    - extensions: Python, Python Docstring Generator, Live Share
- [x] #14
- [x] #13
- [x] #11
- [x] #12

## 2. Part 1 - Prefect Intro
- [x] #2
- [x] #9

## 3. Part 2 - Build a pipeline - existing Airbyte source
Build a full pipeline, eg. API source -> local filesystem -> Metabase.
- [x] #6
Idea for now: source from Strava using Airbyte, sink to Postgres, use DBT to transform, and set up a simple viz in Metabase.
See https://github.com/desertaxle/airbyte-prefect-recipe for Prefect + Airbyte + dbt.
See https://airbyte.io/recipes/build-a-github-activity-dashboard-for-your-project for Airbyte + Metabase.
- [x] #18

## 4. Part 3 - Build a pipeline - new Airbyte source
Create a new API source and build a full pipeline using it, eg. New API source -> local filesystem -> Metabase using.
- [x] #5
- [x] #10

## 5. General
- [x] #16
- [ ] #4
- [x] #3
- [x] #8
- [x] #17

## 6. Next iterations
- [ ] add PR template
- [ ] add mkdocs
- [ ] add CI/CD
- [ ] write a cleanup script
- [ ] add prod tips
- [ ] VSCode set up script (settings, extensions)
- [ ] add part 4 - "Build a library for self-service analytics"
- [ ] use custom app to enter data and serve API
- [ ] consider Dagster
